### ISSUE TITLE
test public github applicaton

### ISSUE THREAD

**Issue by JinroHu** [JinroHu/Test-GithubApplication#1]

**Comment by Hydrion-Qlz** [comment]
this is a new comment generated by program, Received Issue: 1 - opened - test public github applicaton

**Comment by JinroHu** [comment]
got it

**Comment by JinroHu** [comment]
got it

**Comment by JinroHu** [comment]
got it

**Comment by Hydrion-Qlz** [comment]
this is a new comment generated by program, Received Issue: 1 - closed - test public github applicaton
